# Generated by Django 6.0.1 on 2026-02-19 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0004_post_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
    ]
