# Generated by Django 6.0.1 on 2026-02-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0006_photo_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
