# Generated by Django 5.2.12 on 2026-04-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image_url',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='area',
            field=models.CharField(choices=[('Allston', 'Allston'), ('Fenway', 'Fenway'), ('Kenmore', 'Kenmore'), ('Brookline', 'Brookline')], max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(choices=[('American', 'American'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Thai', 'Thai'), ('Vietnamese', 'Vietnamese'), ('Italian', 'Italian'), ('Mexican', 'Mexican'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_level',
            field=models.CharField(choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$')], max_length=10),
        ),
    ]
